/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cocos2dx_cpp_AppActivity */
#include <string>
#ifndef _Included_org_cocos2dx_cpp_AppActivity
#define _Included_org_cocos2dx_cpp_AppActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cocos2dx_cpp_AppActivity
 * Method:    pay_result
 * Signature: (ZLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_cocos2dx_cpp_AppActivity_pay_1result
  (JNIEnv *, jobject, jboolean, jstring);

/*
 * Class:     org_cocos2dx_cpp_AppActivity
 * Method:    init_result
 * Signature: (ZLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_cocos2dx_cpp_AppActivity_init_1result
  (JNIEnv *, jobject, jboolean, jstring);

std::string jstring2str(JNIEnv* env, jstring jstr);
#ifdef __cplusplus
}
#endif
#endif
